name: Karate API Tests
on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch: 
env:
  JAVA_VERSION: '11'
jobs:
  test:
    name: Run Karate Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Java tools
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
          architecture: x64
          overwrite-settings: false
          cache: 'maven'
      - name: Setup Maven
        uses: s4u/maven-settings-action@894661b3ddae382f1ae8edbeab60987e08cf0788
        with:
          mirrors: |
            [{
               "id": "nexus3-wrap-maven",
               "name": "Nexus 3 Wrap Maven group repository",
               "mirrorOf": "*",
               "url": "https://nexus.itt.aws.oprd.com.au/repository/wrap-maven"
            }]
      - name: Tool versions
        run: |
          java -version
          mvn --version
      - name: Install Dependencies
        run: mvn clean install -DskipTests
      
      - name: Run Karate Tests
        run: mvn test -Dkarate.env=dev
      
      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: karate-test-reports
          path: |
            target/karate-reports/
            target/surefire-reports/
          retention-days: 1
